[font]
size = 15

[font.normal]
family = "CodeNewRoman Nerd Font"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"

[window.padding]
x = 4
y = 4

[terminal]
