[font]
size = 15

[font.normal]
family = "CodeNewRoman Nerd Font"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"

[window.padding]
x = 4
y = 4

[terminal]

# This is useful in Claude Code for instance
# to have Shift+Enter create a new line
[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\n"
