export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
HIST_STAMPS="dd/mm/yyyy"
COMPLETION_WAITING_DOTS=true
ZSH_DISABLE_COMPFIX=true

fpath=(/usr/local/share/zsh-completions $fpath)
plugins=(git tmux z)

source $ZSH/oh-my-zsh.sh

export LANG=en_GB.UTF-8
export EDITOR="vim"
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export SSH_KEY_PATH="$HOME/.ssh/id_ed25519.pub"

export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(rbenv init -)"

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

alias brewup="brew update && brew upgrade && brew doctor"
alias gsf="gco staging && git reset --hard origin/master && gm - && gpf"

source $HOME/.local-env-vars
