export ZSH="$HOME/.oh-my-zsh"

DEFAULT_USER="kevin"
ZSH_THEME="agnoster"
HIST_STAMPS="dd/mm/yyyy"
COMPLETION_WAITING_DOTS=true
ZSH_DISABLE_COMPFIX=true

fpath=(/usr/local/share/zsh-completions $fpath)
plugins=(git rails z)

source $ZSH/oh-my-zsh.sh

export LANG=en_GB.UTF-8
export EDITOR="vim"
export PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH"
export SSH_KEY_PATH="$HOME/.ssh/rsa_id.pub"

export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(rbenv init -)"

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

export PATH="$PATH:$HOME/Library/flutter/bin"
export ANDROID_HOME="$HOME/Library/Android"
export PATH="$PATH:$ANDROID_HOME/tools/bin"

alias ag="ag --path-to-ignore ~/.ignore"
alias brewup="brew update && brew upgrade && brew doctor"
alias by="bundle && cd client && yarn && cd .."
alias gsf="gco staging && git reset --hard origin/master && gm - && gpf && gcm"
alias rails="bundle exec rails"
alias rake="bundle exec rake"
alias rdbc="bundle exec rails db:create"
alias rdbd="bundle exec rails db:drop"
alias rdbdc="bundle exec rails db:drop && bundle exec rails db:create"
alias rdbm="bundle exec rails db:migrate && bundle exec rails db:migrate RAILS_ENV=test"
alias rdbrb="bundle exec rails db:rollback && bundle exec rails db:rollback RAILS_ENV=test"
alias rdbs="bundle exec rails db:seed && bundle exec rails db:seed RAILS_ENV=test"
alias rspec="bundle exec rspec"
